#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <nrf24scan_icons.h>
#include "libnrf24/nrf24.h"
#include "zigbee/zigbee.h"

int32_t nrf24scan_app(void* p)
{
    UNUSED(p);

    /* FURI_LOG_I(LOG_TAG,"Init nrf24");
    nrf24_init();
    FURI_LOG_I(LOG_TAG, "NFR24 status : %d", nrf24_status());
    nrf24_set_chan(11);
    FURI_LOG_I(LOG_TAG, "NFR24 current channel : %d", nrf24_get_chan());

    nrf24_set_rx_mode();
    FURI_LOG_I(LOG_TAG, "NFR24 status : %d", nrf24_status()); */

    // Initialize the ZigBee network scanner
    zigbee_scan_init();

    // Start scanning the ZigBee network
    zigbee_scan_network();

    // Print the discovered devices
    zigbee_print_discovered_devices();

    // Deinitialize the nRF24 module
    nrf24_deinit();

    return 0;
}
