#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <nrf24tool_icons.h>
#include "nrf24tool.h"
#include "libnrf24/nrf24.h"

#define MAX_ADDRS            100
#define MAX_CONFIRMED        32
#define LOGITECH_MAX_CHANNEL 78
#define LOGITECH_MIN_CHANNEL 2
#define COUNT_THRESHOLD      2

uint8_t preamble[] = {0xAA, 0x00};

uint8_t candidates[MAX_ADDRS][5] = {0}; // last 100 sniffed addresses
uint32_t counts[MAX_ADDRS];
uint8_t confirmed[MAX_CONFIRMED][5] = {0}; // first 32 confirmed addresses
uint8_t confirmed_idx = 0;
uint32_t total_candidates = 0;
uint32_t candidate_idx = 0;
char top_address[12];
nrf24_data_rate target_rate = DATA_RATE_2MBPS;

NRF24L01_Config sniff = {
    .channel = LOGITECH_MIN_CHANNEL,
    .data_rate = DATA_RATE_2MBPS,
    .tx_power = TX_POWER_0DBM,
    .crc_length = 0,
    .mac_len = ADDR_WIDTH_2_BYTES,
    .arc = 15,
    .ard = 250,
    .auto_ack = {false, false, false, false, false, false},
    .dynamic_payload = {false, false, false, false, false, false},
    .ack_payload = false,
    .tx_no_ack = false,
    .tx_addr = NULL,
    .rx_addr = {preamble, NULL, NULL, NULL, NULL, NULL},
    .payload_size = {MAX_PAYLOAD_SIZE, 0, 0, 0, 0, 0}
};

uint8_t run;

void input_callback(InputEvent* input_event, void* context) {
    UNUSED(context);
    if(input_event->type == InputTypePress) {
        switch(input_event->key) {
            case InputKeyUp:
                break;
            case InputKeyDown:
                break;
            case InputKeyLeft:
                break;
            case InputKeyRight:
                break;
            case InputKeyOk:
                break;
            case InputKeyBack:
                run = 0;
                break;
            case InputKeyMAX:
                break;
        }
    }
}

void hexlify(uint8_t* in, uint8_t size, char* out) {
    const char hex_digits[] = "0123456789ABCDEF";
    
    for (int i = 0; i < size; i++) {
        out[i * 2] = hex_digits[(in[i] >> 4) & 0x0F];
        out[i * 2 + 1] = hex_digits[in[i] & 0x0F];
    }
    out[size * 2] = '\0';
}


int32_t nrf24tool_app(void* p)
{
    UNUSED(p);

    ViewPort* view_port = view_port_alloc();
    view_port_input_callback_set(view_port, input_callback, NULL);

    FURI_LOG_I(LOG_TAG,"Init nrf24");
    nrf24_init();
    FURI_LOG_I(LOG_TAG, "NFR24 status : %d", nrf24_status());
    //nrf24_set_chan(11);
    uint8_t target_channel = LOGITECH_MIN_CHANNEL;
    sniff.channel = target_channel;
    nrf24_configure(&sniff);
    //nrf24_init_promisc_mode(target_channel, 8);
    FURI_LOG_I(LOG_TAG, "NFR24 current channel : %d", nrf24_get_chan());

    nrf24_set_mode(MODE_RX);
    FURI_LOG_I(LOG_TAG, "NFR24 status : %d", nrf24_status());
    

    uint8_t address[5] = {0};
    uint32_t start = 0;
    

    run = 1;

    while(run == 1) {
        if(nrf24_sniff_address(address)) {
            /* FURI_LOG_I(LOG_TAG, "Address Find ! :");
            for(uint8_t i = 0; i < 5; i++)
            {
                FURI_LOG_I(LOG_TAG, "%d", address[i]);
            } */
            int idx;
            uint8_t* top_addr;
            if(!previously_confirmed(address)) {
                idx = get_addr_index(address, 5);
                hexlify(address, 5, top_address);
                FURI_LOG_I(LOG_TAG, "address finded : %s", top_address);
                if(idx == -1)
                    insert_addr(address, 5);
                else
                {
                    counts[idx]++;
                    FURI_LOG_I(LOG_TAG, "address count : %ld", counts[idx]);
                }

                top_addr = candidates[get_highest_idx()];
                hexlify(top_addr, 5, top_address);
                //FURI_LOG_I(LOG_TAG, "top address : %s", top_address);
            }
        }

        if(furi_get_tick() - start >= 4000) {
            target_channel++;
            if(target_channel > LOGITECH_MAX_CHANNEL) target_channel = LOGITECH_MIN_CHANNEL;

            wrap_up();
            sniff.channel = target_channel;
            nrf24_configure(&sniff);
            nrf24_set_mode(MODE_RX);
            //nrf24_init_promisc_mode(target_channel, 8);
            FURI_LOG_I(LOG_TAG, "new channel : %d", nrf24_get_chan());
            start = furi_get_tick();
        }
    }

    // Deinitialize the nRF24 module
    nrf24_deinit();

    view_port_free(view_port);

    return 0;
}
