#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <nrf24scan_icons.h>

int32_t nrf24scan_app(void* p)
{
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm nrf24scan!");

    return 0;
}
