#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <nrf24tool_icons.h>
#include "nrf24tool.h"
#include "libnrf24/nrf24.h"

uint8_t preamble[] = {0xAA, 0x00};

NRF24L01_Config sniff = {
    .channel = 34,
    .data_rate = DATA_RATE_2MBPS,
    .tx_power = TX_POWER_0DBM,
    .crc_length = 0,
    .mac_len = ADDR_WIDTH_2_BYTES,
    .arc = 0,
    .ard = 500,
    .auto_ack = false,
    .dynamic_payload = false,
    .ack_payload = false,
    .tx_no_ack = true,
    .enable_crc = false,
    .tx_addr = NULL,
    .rx_addr = preamble,
    .payload_size = MAX_PAYLOAD_SIZE
};

uint8_t run = 1;

void input_callback(InputEvent* input_event, void* context) {
    UNUSED(context);
    if(input_event->type == InputTypePress) {
        switch(input_event->key) {
            case InputKeyUp:
                break;
            case InputKeyDown:
                break;
            case InputKeyLeft:
                break;
            case InputKeyRight:
                break;
            case InputKeyOk:
                break;
            case InputKeyBack:
                run = 0;
                break;
            case InputKeyMAX:
                break;
        }
    }
}

int32_t nrf24tool_app(void* p)
{
    UNUSED(p);

    ViewPort* view_port = view_port_alloc();
    view_port_input_callback_set(view_port, input_callback, NULL);

    FURI_LOG_I(LOG_TAG,"Init nrf24");
    nrf24_init();
    FURI_LOG_I(LOG_TAG, "NFR24 status : %d", nrf24_status());
    //nrf24_set_chan(11);
    nrf24_configure(&sniff);
    FURI_LOG_I(LOG_TAG, "NFR24 current channel : %d", nrf24_get_chan());

    nrf24_set_mode(MODE_RX);
    FURI_LOG_I(LOG_TAG, "NFR24 status : %d", nrf24_status());
    
    uint8_t packetSize = 0;
    uint8_t packet[MAX_PAYLOAD_SIZE];

    while (packetSize == 0) {
        nrf24_rxpacket(packet, &packetSize, 0);
        FURI_LOG_I(LOG_TAG, "Current packet size : %d", packetSize);
    }

    if (packetSize != 0)
    {
        FURI_LOG_I(LOG_TAG, "Packet found ! size : %d", packetSize);
        for(uint8_t i = 0; i < MAX_PAYLOAD_SIZE; i++)
        {
            FURI_LOG_I(LOG_TAG, "Packet [%d] : %d", i, packet[i]);
        }
    }

    // Deinitialize the nRF24 module
    nrf24_deinit();

    view_port_free(view_port);

    return 0;
}
